x-airflow-common: &airflow-common
  build: .
  environment:
    &airflow-common-env
    PYTHONPATH: /opt/airflow/dags
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE_DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__IS_PAUSED_UPON_CREATION: 'true'
    AIRFLOW__CORE_LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.session,airflow.api.auth.backend.basic_auth'
    AIRFLOW__WEBSERVER__RBAC: 'True'
    # OTIMIZAÇÃO VPS: Usa as 4 vCPUs para processar tarefas em paralelo
    AIRFLOW__CORE__PARALLELISM: 4
    AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 4
    GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/keys/sa-airflow.json
    BUCKET_LANDING: ${BUCKET_LANDING}
    BUCKET_BRONZE: ${BUCKET_BRONZE}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
    AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT: ${AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT}
    AIRFLOW__LOGGING__LOG_FETCHING_TIMEOUT: 10
    AIRFLOW__PROVIDERS_ODBC__ALLOW_DRIVER_IN_EXTRA: 'true'
    DREMIO_USER: ${DREMIO_USER}
    DREMIO_PASSWORD: ${DREMIO_PASSWORD}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./keys:/opt/airflow/keys
    # - ./webserver_config.py:/opt/airflow/webserver_config.py
  user: "${AIRFLOW_UID:-50000}:0"
  deploy:
    resources:
      limits:
        memory: 2G # Limite de Segurança para o Airflow
  depends_on:
    # &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  # --- METADADOS (AIRFLOW) ---
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./data_volumes/postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M #Pg aguenta bem com pouca RAM para metadados
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    restart: always

  # --- ORQUESTRAÇÃO ---
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    environment:
      <<: *airflow-common-env
      AIRFLOW__CORE__TEST_CONNECTION: ${AIRFLOW__CORE__TEST_CONNECTION}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
      airflow-cli:
        condition: service_completed_successfully
    environment:
      <<: *airflow-common-env
    command: scheduler
    restart: always

  airflow-cli:
    <<: *airflow-common
    environment:
      <<: *airflow-common-env
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "airflow db init && airflow users list | grep -q 'admin' ||
      airflow users create --username admin --firstname MVP --lastname 'Rio Viagens' --role Admin --email admin@example.com --password admin"

  # --- LAKEHOUSE ENGINE ---
  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio
    user: root
    ports:
      - "9047:9047"
      - "31010:31010"
      - "32010:32010"
    environment:
      # A MÁGICA DA ECONOMIA AQUI:
      # TUNING JVM VPS:
      # Heap de 2.5GB (Processamento) + 1GB Direct (Cache/IO)
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Xms1024m -Xmx2560m -XX:MaxDirectMemorySize=1024m
      - DREMIO_JAVA_EXTRA_OPTS=-Dauth.personal_access_tokens.enabled=true -Dcom.dremio.file.permission.check.disabled=true
    volumes:
      - ./data_volumes/dremio_data:/opt/dremio/data
      - ./keys/sa-dremio.json:/opt/dremio/keys/sa-dremio.json
    deploy:
      resources:
        limits:
          memory: 12G # Permitimos usar até 4.5GB (usando swap se precisar)
    restart: unless-stopped
  # --- DATA CATALOG (GIT FOR DATA) ---
  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    container_name: nessie
    restart: always
    depends_on:
      - postgres
    ports:
      - "19120:19120"
    environment:
      # Define a persistência como JDBC
      - NESSIE_VERSION_STORE_TYPE=JDBC
      # URL de conexão (db é o nome do serviço no compose)
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/nessie
      - QUARKUS_DATASOURCE_USERNAME=nessie
      - QUARKUS_DATASOURCE_PASSWORD=nessie
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      # Instrução para criar as tabelas automaticamente
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update
  # --- Ferramenta de BI ---
  superset:
    image: apache/superset:latest
    container_name: superset
    restart: always
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
      # Configurando o Postgres existente para o Superset
      - SQLALCHEMY_DATABASE_URI=postgresql://superset:superset@postgres:5432/superset
    user: "root"
    entrypoint: >
      /bin/sh -c "
        superset db upgrade;
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@fab.org --password admin;
        superset init;
        /usr/bin/run-server.sh --host 0.0.0.0 --port 8088 --with-threads"
    depends_on:
      - postgres
  # --- GESTÃO VISUAL ---
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data_volumes/portainer_data:/data
    restart: always

networks:
  default:
    name: mvp_network
